const actionType =  { 
  GET_WECHATACCOUNT_LIST_START:'GET_WECHATACCOUNT_LIST_START',
  GET_WECHATACCOUNT_LIST_LOADING:'GET_WECHATACCOUNT_LIST_LOADING',
  GET_WECHATACCOUNT_LIST_END:'GET_WECHATACCOUNT_LIST_END',
  GET_WECHATACCOUNT_START:'GET_WECHATACCOUNT_START',
  GET_WECHATACCOUNT_LOADING:'GET_WECHATACCOUNT_LOADING',
  GET_WECHATACCOUNT_END:'GET_WECHATACCOUNT_END',
  CLEAR_WECHATACCOUNT:'CLEAR_WECHATACCOUNT',
  UPDATE_WECHATACCOUNT_START:'UPDATE_WECHATACCOUNT_START',
  UPDATE_WECHATACCOUNT_LOADING:'UPDATE_WECHATACCOUNT_LOADING',
  UPDATE_WECHATACCOUNT_END:'UPDATE_WECHATACCOUNT_END',
  UPDATE_MSG_SHOW_STATE:'UPDATE_MSG_SHOW_STATE',
  ADD_WECHATACCOUNT_START:'ADD_WECHATACCOUNT_START',
  ADD_WECHATACCOUNT_LOADING:'ADD_WECHATACCOUNT_LOADING',
  ADD_WECHATACCOUNT_END:'ADD_WECHATACCOUNT_END',
}

export default actionType